// Mock data for development - structured for easy AWS migration
import type { 
  Testimonial, 
  Theme, 
  CountryOption, 
  LanguageOption, 
  SpecialtyOption 
} from './types';

// Sample testimonials with global distribution
export const mockTestimonials: Testimonial[] = [
  {
    id: '1',
    metadata: {
      country: 'US',
      careerStage: 'Mid-career',
      specialty: 'Internal Medicine',
      language: 'en',
      practiceSetting: 'academic',
    },
    highlight: 'AI helped me catch a rare diagnosis that I might have missed during a busy shift.',
    submittedAt: '2026-02-01T10:30:00Z',
    coordinates: { lat: 40.7128, lng: -74.006 },
    themeIds: ['1', '3'],
  },
  {
    id: '2',
    metadata: {
      country: 'GB',
      careerStage: 'Senior',
      specialty: 'Radiology',
      language: 'en',
      practiceSetting: 'community',
    },
    highlight: 'The AI reading assistant has transformed how we prioritize urgent scans.',
    submittedAt: '2026-02-02T14:15:00Z',
    coordinates: { lat: 51.5074, lng: -0.1278 },
    themeIds: ['2'],
  },
  {
    id: '3',
    metadata: {
      country: 'IN',
      careerStage: 'Trainee',
      specialty: 'Pediatrics',
      language: 'hi',
      practiceSetting: 'rural',
    },
    highlight: 'AI-powered triage helps us serve patients in remote areas with limited specialists.',
    submittedAt: '2026-02-03T08:45:00Z',
    coordinates: { lat: 28.6139, lng: 77.209 },
    themeIds: ['1', '4'],
  },
  {
    id: '4',
    metadata: {
      country: 'BR',
      careerStage: 'Early-career',
      specialty: 'Emergency Medicine',
      language: 'pt',
      practiceSetting: 'urban',
    },
    highlight: 'AI assists with language barriers when treating patients from different regions.',
    submittedAt: '2026-02-03T16:20:00Z',
    coordinates: { lat: -23.5505, lng: -46.6333 },
    themeIds: ['4', '5'],
  },
  {
    id: '5',
    metadata: {
      country: 'JP',
      careerStage: 'Senior',
      specialty: 'Oncology',
      language: 'ja',
      practiceSetting: 'academic',
    },
    highlight: 'Machine learning models help predict treatment responses for complex cancer cases.',
    submittedAt: '2026-02-04T09:10:00Z',
    coordinates: { lat: 35.6762, lng: 139.6503 },
    themeIds: ['3', '6'],
  },
  {
    id: '6',
    metadata: {
      country: 'DE',
      careerStage: 'Mid-career',
      specialty: 'Cardiology',
      language: 'de',
      practiceSetting: 'private',
    },
    highlight: 'ECG interpretation AI has become an invaluable second opinion in my practice.',
    submittedAt: '2026-02-04T11:30:00Z',
    coordinates: { lat: 52.52, lng: 13.405 },
    themeIds: ['2', '3'],
  },
  {
    id: '7',
    metadata: {
      country: 'NG',
      careerStage: 'Early-career',
      specialty: 'Family Medicine',
      language: 'en',
      practiceSetting: 'community',
    },
    highlight: 'AI diagnostic support is bridging the specialist gap in underserved communities.',
    submittedAt: '2026-02-05T07:45:00Z',
    coordinates: { lat: 6.5244, lng: 3.3792 },
    themeIds: ['1', '4'],
  },
  {
    id: '8',
    metadata: {
      country: 'AU',
      careerStage: 'Trainee',
      specialty: 'Dermatology',
      language: 'en',
      practiceSetting: 'academic',
    },
    highlight: 'Image recognition AI helps me learn to identify rare skin conditions faster.',
    submittedAt: '2026-02-05T13:20:00Z',
    coordinates: { lat: -33.8688, lng: 151.2093 },
    themeIds: ['2', '5'],
  },
];

// Theme categorizations
export const mockThemes: Theme[] = [
  {
    id: '1',
    title: 'Diagnostic Accuracy',
    description: 'AI improving diagnostic precision and catching missed diagnoses',
    count: 3,
    isNew: false,
    isEmerging: true,
  },
  {
    id: '2',
    title: 'Workflow Efficiency',
    description: 'AI streamlining clinical workflows and reducing administrative burden',
    count: 3,
    isNew: true,
    isEmerging: true,
  },
  {
    id: '3',
    title: 'Clinical Decision Support',
    description: 'AI providing second opinions and treatment recommendations',
    count: 3,
    isNew: false,
    isEmerging: false,
  },
  {
    id: '4',
    title: 'Healthcare Access',
    description: 'AI bridging gaps in healthcare access and specialist availability',
    count: 3,
    isNew: true,
    isEmerging: true,
  },
  {
    id: '5',
    title: 'Medical Education',
    description: 'AI enhancing learning and training for medical professionals',
    count: 2,
    isNew: true,
    isEmerging: false,
  },
  {
    id: '6',
    title: 'Precision Medicine',
    description: 'AI enabling personalized treatment approaches',
    count: 1,
    isNew: false,
    isEmerging: true,
  },
];

// Commonly used countries (ISO 3166-1)
export const countries: CountryOption[] = [
  { code: 'US', name: 'United States' },
  { code: 'GB', name: 'United Kingdom' },
  { code: 'CA', name: 'Canada' },
  { code: 'AU', name: 'Australia' },
  { code: 'DE', name: 'Germany' },
  { code: 'FR', name: 'France' },
  { code: 'JP', name: 'Japan' },
  { code: 'IN', name: 'India' },
  { code: 'BR', name: 'Brazil' },
  { code: 'CN', name: 'China' },
  { code: 'ZA', name: 'South Africa' },
  { code: 'NG', name: 'Nigeria' },
  { code: 'KE', name: 'Kenya' },
  { code: 'MX', name: 'Mexico' },
  { code: 'AR', name: 'Argentina' },
  { code: 'ES', name: 'Spain' },
  { code: 'IT', name: 'Italy' },
  { code: 'NL', name: 'Netherlands' },
  { code: 'SE', name: 'Sweden' },
  { code: 'NO', name: 'Norway' },
  { code: 'DK', name: 'Denmark' },
  { code: 'FI', name: 'Finland' },
  { code: 'CH', name: 'Switzerland' },
  { code: 'AT', name: 'Austria' },
  { code: 'BE', name: 'Belgium' },
  { code: 'PL', name: 'Poland' },
  { code: 'RU', name: 'Russia' },
  { code: 'KR', name: 'South Korea' },
  { code: 'SG', name: 'Singapore' },
  { code: 'MY', name: 'Malaysia' },
  { code: 'TH', name: 'Thailand' },
  { code: 'ID', name: 'Indonesia' },
  { code: 'PH', name: 'Philippines' },
  { code: 'VN', name: 'Vietnam' },
  { code: 'EG', name: 'Egypt' },
  { code: 'AE', name: 'United Arab Emirates' },
  { code: 'SA', name: 'Saudi Arabia' },
  { code: 'IL', name: 'Israel' },
  { code: 'TR', name: 'Turkey' },
  { code: 'GR', name: 'Greece' },
  { code: 'PT', name: 'Portugal' },
  { code: 'IE', name: 'Ireland' },
  { code: 'NZ', name: 'New Zealand' },
  { code: 'CL', name: 'Chile' },
  { code: 'CO', name: 'Colombia' },
  { code: 'PE', name: 'Peru' },
];

// Common languages (ISO 639-1)
export const languages: LanguageOption[] = [
  { code: 'en', name: 'English' },
  { code: 'es', name: 'Spanish' },
  { code: 'fr', name: 'French' },
  { code: 'de', name: 'German' },
  { code: 'pt', name: 'Portuguese' },
  { code: 'zh', name: 'Chinese (Mandarin)' },
  { code: 'ja', name: 'Japanese' },
  { code: 'ko', name: 'Korean' },
  { code: 'ar', name: 'Arabic' },
  { code: 'hi', name: 'Hindi' },
  { code: 'ru', name: 'Russian' },
  { code: 'it', name: 'Italian' },
  { code: 'nl', name: 'Dutch' },
  { code: 'sv', name: 'Swedish' },
  { code: 'pl', name: 'Polish' },
  { code: 'tr', name: 'Turkish' },
  { code: 'th', name: 'Thai' },
  { code: 'vi', name: 'Vietnamese' },
  { code: 'id', name: 'Indonesian' },
  { code: 'ms', name: 'Malay' },
  { code: 'tl', name: 'Tagalog' },
  { code: 'sw', name: 'Swahili' },
  { code: 'he', name: 'Hebrew' },
  { code: 'el', name: 'Greek' },
  { code: 'cs', name: 'Czech' },
  { code: 'hu', name: 'Hungarian' },
  { code: 'ro', name: 'Romanian' },
  { code: 'uk', name: 'Ukrainian' },
  { code: 'bn', name: 'Bengali' },
  { code: 'ta', name: 'Tamil' },
];

// Medical specialties (controlled vocabulary)
export const specialties: SpecialtyOption[] = [
  { value: 'internal-medicine', label: 'Internal Medicine' },
  { value: 'family-medicine', label: 'Family Medicine' },
  { value: 'pediatrics', label: 'Pediatrics' },
  { value: 'emergency-medicine', label: 'Emergency Medicine' },
  { value: 'surgery-general', label: 'General Surgery' },
  { value: 'cardiology', label: 'Cardiology' },
  { value: 'oncology', label: 'Oncology' },
  { value: 'radiology', label: 'Radiology' },
  { value: 'pathology', label: 'Pathology' },
  { value: 'dermatology', label: 'Dermatology' },
  { value: 'neurology', label: 'Neurology' },
  { value: 'psychiatry', label: 'Psychiatry' },
  { value: 'ob-gyn', label: 'Obstetrics & Gynecology' },
  { value: 'anesthesiology', label: 'Anesthesiology' },
  { value: 'orthopedics', label: 'Orthopedics' },
  { value: 'ophthalmology', label: 'Ophthalmology' },
  { value: 'ent', label: 'Otolaryngology (ENT)' },
  { value: 'urology', label: 'Urology' },
  { value: 'nephrology', label: 'Nephrology' },
  { value: 'gastroenterology', label: 'Gastroenterology' },
  { value: 'pulmonology', label: 'Pulmonology' },
  { value: 'endocrinology', label: 'Endocrinology' },
  { value: 'rheumatology', label: 'Rheumatology' },
  { value: 'infectious-disease', label: 'Infectious Disease' },
  { value: 'critical-care', label: 'Critical Care Medicine' },
  { value: 'geriatrics', label: 'Geriatrics' },
  { value: 'palliative', label: 'Palliative Care' },
  { value: 'sports-medicine', label: 'Sports Medicine' },
  { value: 'physical-medicine', label: 'Physical Medicine & Rehabilitation' },
  { value: 'public-health', label: 'Public Health' },
  { value: 'other', label: 'Other' },
];

// Country coordinates for mapping (simplified)
export const countryCoordinates: Record<string, { lat: number; lng: number }> = {
  US: { lat: 37.0902, lng: -95.7129 },
  GB: { lat: 55.3781, lng: -3.436 },
  CA: { lat: 56.1304, lng: -106.3468 },
  AU: { lat: -25.2744, lng: 133.7751 },
  DE: { lat: 51.1657, lng: 10.4515 },
  FR: { lat: 46.2276, lng: 2.2137 },
  JP: { lat: 36.2048, lng: 138.2529 },
  IN: { lat: 20.5937, lng: 78.9629 },
  BR: { lat: -14.235, lng: -51.9253 },
  CN: { lat: 35.8617, lng: 104.1954 },
  ZA: { lat: -30.5595, lng: 22.9375 },
  NG: { lat: 9.082, lng: 8.6753 },
  KE: { lat: -0.0236, lng: 37.9062 },
  MX: { lat: 23.6345, lng: -102.5528 },
  AR: { lat: -38.4161, lng: -63.6167 },
  ES: { lat: 40.4637, lng: -3.7492 },
  IT: { lat: 41.8719, lng: 12.5674 },
};
